### ISSUE TITLE
v2.0版本 

### ISSUE THREAD

**Issue by hfhzzdx** [lihanghang/CASR-DEMO#43]
2.0的demo中manage.py主程序中导入的三方库是哪个? 
自己没有找到,并且项目中没有这个包
from Speaker_Recognition import register, speakerrecog # 声纹识别库

![image](https://user-images.githubusercontent.com/44967393/133766055-8bb11b8f-1211-4af1-b134-26154ee70c53.png)

**Comment by Zony-Zhao** [comment]
解决了吗?同问

**Comment by mjwSilence** [comment]
同问 +1，看来是没有解决了

**Comment by beggin0516** [comment]
这里不是应该是那个两个py文件有些库没装吗

**Comment by beggin0516** [comment]
把那个文件里面的库装完就行了吧

**Comment by lihanghang** [comment]
我来看看，这个包应该是路径问题。

**Comment by lihanghang** [comment]
修改了导包路径，大家试试> 
from SR import register, speakerrecog # 声纹识别库

**Comment by lihanghang** [comment]
> 2.0的demo中manage.py主程序中导入的三方库是哪个? 自己没有找到,并且项目中没有这个包 from Speaker_Recognition import register, speakerrecog # 声纹识别库
> 
> ![image](https://user-images.githubusercontent.com/44967393/133766055-8bb11b8f-1211-4af1-b134-26154ee70c53.png)

修改了导包路径，大家试试>
from SR import register, speakerrecog # 声纹识别库
