### ISSUE TITLE
项目Speech2.0的相关问题

### ISSUE THREAD

**Issue by Butterlor** [lihanghang/CASR-DEMO#9]
大神您好，我想请问一下您这个项目是要部署到服务器上的是吗，我不知道该部署哪些文件到网站上，因为speechV2.0有太多文件了，还有文档，有点看不懂，还望您多多指点。
还有，我不明白白的一点是，您这个部署到服务器后，它所需要的功能库也是需要在网站上进行安装才能正常运行的是吗

**Comment by lihanghang** [comment]
感谢关注。确实有点乱，我后续整理下。
项目没在服务器上试过，只在win10平台上跑过，注意下相关包可能更新或者用法有变，调试下就行。然后主入口是manage.py文件。
